urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    url(r'^accounts/profile/$', 'djauction.views.profile'),
    url(r'^adduser/$', 'djauction.views.add_user'),
    url(r'^addauction/$', 'djauction.views.add_auction'),
    url(r'^auction/(\d+)/addevent/$', 'djauction.views.add_event'),
    url(r'^auction/(\d+)/bids/export/$', 'djauction.views.export_bids'),
    url(r'^auction/(\d+)/checkin/$', 'djauction.views.checkin_user'),
    url(r'^auction/(\d+)/event/(\d+)/$', 'djauction.views.view_event'),
    url(r'^auction/(\d+)/item/bulkadd/$', 'djauction.views.bulk_add_item'),
    url(r'^auction/(\d+)/listevents/$', 'djauction.views.list_events'),
    url(r'^auction/(\d+)/listusers/$', 'djauction.views.list_users'),
    url(r'^auction/(\d+)/listitems/$', 'djauction.views.list_items'),
    url(r'^auction/(\d+)/userpaid/$', 'djauction.views.user_paid_view'),
    url(r'^auction/(\d+)/user/(\d+)/additem/$', 'djauction.views.add_item'),
    url(r'^auction/(\d+)/user/(\d+)/checkout/$', 'djauction.views.checkout_user'),
    url(r'^auction/sendemail/$', 'djauction.views.send_email'),
    url(r'^auction/(\d+)/$', 'djauction.views.view_auction'),
    url(r'^user/(\d+)/auction/(\d+)/$', 'djauction.views.view_user'),
    url(r'^user/bulkadd/$', 'djauction.views.bulk_add_user'),
    url(r'^user/(\d+)/$', 'djauction.views.view_user'),
    url(r'^item/(\d+)/$', 'djauction.views.view_item'),
    url(r'^$', 'djauction.views.index'),
)

models.py
from django.db import models

STATE_CHOICES = (
    ('pa', 'Pennsylvania'),
    ('nj', 'New Jersey'),
)

ITEM_CHOICES = (
    ('event','Event'),
    ('food','Food'),
    ('goods','Goods'),
    ('service','Service'),
    ('other','Other'),
)

PAYMENT_CHOICES = (
    ('none','None'),
    ('cash','Cash'),
    ('check','Check'),
    ('credit','Credit'),
)

class Auction(models.Model):

    ''' Model to represent an Auction '''

    name = models.CharField(max_length=255)
    date = models.DateField()

    def __unicode__(self):
        return self.name + ' ' + str(self.date)

class AuctionUser(models.Model):

    ''' Model to represent an Auction User; i.e. someone who donates
        or bids on users '''

    name = models.CharField(max_length=255)
    address_1 = models.CharField(max_length=255, blank=True)
    address_2 = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=255, blank=True)
    state = models.CharField(max_length=2, choices=STATE_CHOICES,
        blank=True)
    zip = models.CharField(max_length=10, blank=True)
    phone = models.CharField(max_length=255, blank=True)
    email = models.EmailField(max_length=255, blank=True)

    def __unicode__(self):
        return self.name

class AuctionParticipant(models.Model):

    ''' Model to represent an Auction Participant; i.e. someone who
        will be bidding on items in the auction '''

    auction = models.ForeignKey(Auction)
    user = models.ForeignKey(AuctionUser)
    paddle = models.PositiveIntegerField()
    payment_method = models.CharField(max_length=10, choices=PAYMENT_CHOICES,
        default='none')
    payment_notes = models.TextField(blank=True)

    def __unicode__(self):
        #return str(self.user) + ' (' + str(self.paddle) + ')'
        return "{:_>4}:  {}".format(self.paddle,self.user)

class AuctionEvent(models.Model):

    ''' Model to represent an Auction Event; i.e. a collection of items
        that will be bid on during the auction '''

    name = models.CharField(max_length=255)
    abbreviation = models.CharField(max_length=10)
    auction = models.ForeignKey(Auction)

    def __unicode__(self):
        return self.name + ' ' + self.abbreviation

class AuctionItem(models.Model):

    ''' Model to represent an Item to be bid on in an auction '''

    name = models.CharField(max_length=255)
    item_type = models.CharField(max_length=20, choices=ITEM_CHOICES)
    item_number = models.IntegerField()
    description = models.TextField(blank=True)
    image = models.ImageField(max_length=255,upload_to='images',blank=True)
    valid_winners = models.PositiveIntegerField(default=1)
    auction = models.ForeignKey(Auction)
    auction_event = models.ForeignKey(AuctionEvent)
    donor = models.ForeignKey(AuctionUser)
    starting_bid = models.FloatField()
    conditions = models.TextField(blank=True)
    time_and_location = models.TextField(blank=True)

    def __unicode__(self):
        return str(self.auction_event.abbreviation) + str(self.item_number) + ' ' + self.name

class AuctionBid(models.Model):

    ''' Model to represent an individual Bid in an Auction '''

    auction = models.ForeignKey(Auction)
    bidder = models.ForeignKey(AuctionParticipant)
    item = models.ForeignKey(AuctionItem)
    ammount = models.FloatField()

    def __unicode__(self):
        return "${:5,.0f} by {}".format(self.ammount, self.bidder)

templates/djauction/addauction.html
{% extends "djauction/base.html" %}
{% block content %}
    <form action="." method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    <p><a href="{% url 'djauction.views.index' %}">Back To Auction Manager</a></p>
{% endblock %}

templates/djauction/additem.html
{% extends "djauction/base.html" %}
{% block content %}
    <form action="{% url 'djauction.views.add_item' auction.id auction_user.id %}" method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit"/>
    </form>
    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>
{% endblock %}

templates/djauction/adduser.html
{% extends "djauction/base.html" %}
{% block content %}
    <form action="." method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    <p><a href="{% url 'djauction.views.index' %}">Back To Index</a></p>
{% endblock %}

templates/djauction/bulkadditem.html
{% extends "djauction/base.html" %}
{% block content %}
    <h3>Bulk Import Items</h3>
    <p>Add items in a .csv file, one user per line, in the following format<br>
    <b>item_name,auction_event,item_number,item_type,donor,valid_winners,starting_bid,time_and_location,conditions</b></p>
    {% for line in status %}
    <li>{{ line }}</li>
    {% endfor %}
    {% if form %}
    <form action="{% url 'djauction.views.bulk_add_item' auction.id %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Import"/>
    </form>
    {% endif %}
{% endblock %}

templates/djauction/bulkadduser.html
{% extends "djauction/base.html" %}
{% block content %}
    <h3>Bulk Import Users</h3>
    <p>Add users in a .csv file, one user per line, in the following format<br>
    <b>name,phone,email</b></p>
    {% for line in status %}
    <li>{{ line }}</li>
    {% endfor %}
    {% if form %}
    <form action="{% url 'djauction.views.bulk_add_user' %}" method="post" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Import"/>
    </form>
    {% endif %}
{% endblock %}

templates/djauction/checkinuser.html
{% extends "djauction/base.html" %}
{% block content %}
    {% for error in errors %}
    <li>{{ error }}</li>
    {% endfor %}
    <form action="." method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
    </form>
    <p><a href="{% url 'djauction.views.list_users' auction.id %}">Back To Bidder List</a></p>
{% endblock %}

templates/djauction/checkoutuser.html
{% extends "djauction/base.html" %}
{% block content %}
    <h3>{{ auction_user }}</h3>

    {% if winning_users %}
        <h3>Bidders Who Won Items From {{ auction_user }}</h3>
        {% for user in winning_users %}
            <p>
            <a href="{% url 'djauction.views.view_user' user.id auction.id %}">{{ user }}</a><br>
            {{user.phone}} <a href="mailto:{{user.email}}">{{user.email}}</a>
            </p>
        {% endfor %}
    {% endif %}

    {% if winning_bids %}
        <h3>Items Won From {{ auction_user }}</h3>
        {% for bid in winning_bids %}
            <li><a href={% url 'djauction.views.view_item' bid.item.id %}>{{ bid.item }}</a></li>
        {% endfor %}
    {% endif %}

    {% if won_users %}
        <h3>Donors Who {{ auction_user }} Won Items From</h3>
        {% for user in won_users %}
            <p>
            <a href="{% url 'djauction.views.view_user' user.id auction.id %}">{{ user }}</a><br>
            {{user.phone}} <a href="mailto:{{user.email}}">{{user.email}}</a>
            </p>
        {% endfor %}
    {% endif %}

    {% if user_bids %}
        <h3>Items Won</h3>
        <table>
        {% for bid in user_bids %}
            <tr>
            <td><a href="{% url 'djauction.views.view_item' bid.item.id %}">{{bid.item}}</a></td>
            <td>{{bid.ammount}}</td>
        {% endfor %}
        </table>
        Total Due: {{ owed|default:"0" }}<br>
        <h3>Update Payment Info</h3>
        <div style="width:500px;border:6px outset blue;">
        <form action="." method="post">{% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Update" />
        </form>
        </div>

    {% endif %}

    {% if user.email %}
    <br>
    <h3>Email Reciept</h3>
    <div style="border:6px outset blue;">
    TO: {{ user.email }} <br>
    SUBJECT: Auction Reciept from {{ auction.date }} <br>
    <br>
    {% include "djauction/emailtemplate.html" %}
    </div>
    <!--
    <form method="post" action="{% url 'djauction.views.send_email' %}">{% csrf_token %}
        <input type="submit" value="Send Email Receipt">
    </form>
    -->
    {% endif %}

    <p><a href="{% url 'djauction.views.view_user' auction_user.id auction.id %}">Back To Bidder Info</a></p>
{% endblock %}

templates/djauction/emailtemplate.html
Dear {{ auction_user }},<br>
<br>
Thank you for joining us at this year's auction! It was great to have you.<br>
<br>

<!-- If the user won items, render this -->
{% if user_bids %}
Here's what you won:<br>
{% for bid in user_bids %}
{{ bid.item }} for ${{ bid.ammount }} Donated By {{ bid.item.donor }} {{ bid.item.donor.email }} {{ bid.item.donor.phone }} <br>
{% if bid.item.time_and_location %}
Time and Location: {{ bid.item.time_and_location }}<br>
{% endif %}
{% if bid.item.conditions %}
{{ bid.item.conditions }}<br>
{% endif %}
{% endfor %}
<br>
{% endif %}

<!-- If the winner's donations sold, render this -->
{% if winning_bids %}
We're grateful for your donations to the auction, too. Here's how they did<br>
{% for bid in winning_bids %}
{{ bid.item }} for {{ bid.ammount }} Won by {{ bid.bidder.user }} {{ bid.bidder.user.email }} {{ bid.bidder.user.phone }}<br>
{% endfor %}
<br>
{% endif %}

<!-- Tell the user if they have paid or not -->
{% if owed > 0 %}
{% if paddle.payment_method != 'none' %}
Our records indicate you have paid for your items won.<br>
{% else %}
Our records indicate you have yet to pay for your items. You owe and outstanding balance of {{ owed }}. Please pay at your earliest convenience.<br>
{% endif %}
<br>
{% endif %}

If you have any questions, just let us know. Thank you again for supporting us at the auction!<br>

templates/djauction/listitems.html
{% extends "djauction/base.html" %}
{% block content %}
    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>
    {% if del_items %}
        <b>Warning: This will delete the following items and all bids for them. This can not be undone.</b><br>
        <form action="{% url 'djauction.views.list_items' auction.id %}" method="post">{% csrf_token %}
        {% for item in del_items %}
            <li>{{item}}</li>
            <input type="hidden" name="del_items" value="{{item.id}}">
        {% endfor %}
        <input type="submit" value="Delete" name="delete_confirm">
        </form>
        <a href="{% url 'djauction.views.list_items' auction.id %}">Cancel</a>
    {% else %}
        <h3>Items</h3>
        {% if items %}
            <form action="{% url 'djauction.views.list_items' auction.id %}" method="post">{% csrf_token %}
            {% for item in items %}
            <input type="checkbox" name="del_items" value="{{item.id}}">
            <a href="{% url 'djauction.views.view_item' item.id %}">{{ item }}</a><br>
            {% endfor %}
            <input type="submit" value="Delete"><br>
            </form>
        {% else %}
            No items found<br>
        {% endif %}
    {% endif %}
    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>
{% endblock %}

templates/djauction/listusers.html
{% extends "djauction/base.html" %}
{% block content %}
    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>
    <p><a href="{% url 'djauction.views.checkin_user' auction.id %}">Check In A New Bidder</a></p>
    <h3>Bidders</h3>
    {% for participant in participants %}
    <a href="{% url 'djauction.views.view_user' participant.user.id auction.id %}">{{ participant.paddle}} {{ participant.user }}</a><br>
    {% empty %}
    No users found<br>
    {% endfor %}
    <p><a href="{% url 'djauction.views.checkin_user' auction.id %}">Check In A New Bidder</a></p>
    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>
{% endblock %}

templates/djauction/viewauction.html
{% extends "djauction/base.html" %}
{% block content %}
    <h3>{{ auction }}</h3>
    <li><a href="{% url 'djauction.views.list_events' auction.id %}">Manage Events</a></li>
    <li><a href="{% url 'djauction.views.list_users' auction.id %}">Manage Bidders</a></li>
    <li><a href="{% url 'djauction.views.list_items' auction.id %}">Manage Items</a></li>
    <p>Net Earned: ${{ net_earned }}</p>
    <p><a href="{% url 'djauction.views.index' %}">Back To Index</a></p>
{% endblock %}

templates/djauction/viewevent.html
{% extends "djauction/base.html" %}
{% block content %}
<h3>Items</h3>
{% for item in items %}
<li><a href="{% url 'djauction.views.view_item' item.id %}">{{ item }}</a></li>
{% empty %}
No items configured<br>
{% endfor %}
<p><a href="{% url 'djauction.views.list_events' auction.id %}">Back To Events List</a></p>
{% endblock %}

templates/djauction/viewitem.html
{% extends "djauction/base.html" %}
{% block content %}

    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>

    <table width="100%">
        <tr>
            <td align="left">
            {% if prev_item %}
                <a href="{% url 'djauction.views.view_item' prev_item.id %}">Previous ({{ prev_item }})</a>
            {% endif %}
            </td>
            <td align="right">
            {% if next_item %}
                <a href="{% url 'djauction.views.view_item' next_item.id %}">Next ({{ next_item }})</a>
            {% endif %}
            </td>
        </tr>
    </table>
    <br>

    <h3> {{ item }} </h3>
    Donated by <a href="{% url 'djauction.views.view_user' donor.id auction.id %}">{{donor}}</a><br>
    {% if item.image %}
        <p><img src="{{ MEDIA_URL }}/{{item.image}}"/></p>
    {% endif %}
    {% if item.time_and_location %}
    Description: {{item.description}}<br>
    {% endif %}
    {% if item.time_and_location %}
    Time and Location: {{item.time_and_location}}<br>
    {% endif %}
    {% if item.conditions %}
    Conditions: {{item.conditions}}<br>
    {% endif %}

    {% if item.starting_bid %}
    <h4>Starting Bid: ${{item.starting_bid}}</h4>
    {% else %}
    <h4>(No starting bid provided)</h4>
    {% endif %}

    {% if bid_del_form %}
    <h3>Current Bids (max bids = {{item.valid_winners}})</h3>
        <form action="{% url 'djauction.views.view_item' item.id %}" method="post">{% csrf_token %}
        <table width="100%">
            <tr align="left"><th>Amount, by Paddle #: Bidder</th></tr>
            <tr>
            {% for field in bid_del_form %}
                <td>{{field}}</td>
            {% endfor %}
            </tr>
            <tr><td><input type="submit" value="Delete" name="del_bids"/></td></tr>
        </table>
        </form>
    {% endif %}

    {% if bid_add_form %}
        {% if bid_del_form %}
    <h3>Enter Remaining Bids (up to max total of {{item.valid_winners}} bids)</h3>
        {% else %}
    <h3>Enter New Bids (up to max of {{item.valid_winners}} bids)</h3>
        {% endif %}
        <table>
        <form action="{% url 'djauction.views.view_item' item.id %}" method="post">{% csrf_token %}
            {% for field in bid_add_form %}
            {% cycle 'field_left' 'field_right' as curfield silent %}
            {% if curfield == "field_left" %}
            <tr><td>{{field}}</td>
            {% else %}
            &nbsp;&nbsp;<td>${{field}}</td></tr>
            {% endif %}
            {% endfor %}
            <tr><td><input type="submit" value="Submit Bids" name="add_bids"/></td></tr>
        </form>
        </table>
    {% endif %}

    <h3>Add Bid Manually (overrides max bid limit)</h3>
    <table>
        <form action="{% url 'djauction.views.view_item' item.id %}" method="post">{% csrf_token %}
            <tr>
                <td>{{manual_bid_form.bidder}}</td>&nbsp;&nbsp;<td>${{manual_bid_form.ammount}}</td>
            </tr>
            <tr><td><input type="submit" value="Add Bid" name="manual_add_bid"></td></tr>
        </form>
    </table>
    <br>

    <table width="100%">
        <tr>
            <td align="left">
            {% if prev_item %}
                <a href="{% url 'djauction.views.view_item' prev_item.id %}">Previous ({{ prev_item }})</a>
            {% endif %}
            </td>
            <td align="right">
            {% if next_item %}
                <a href="{% url 'djauction.views.view_item' next_item.id %}">Next ({{ next_item }})</a>
            {% endif %}
            </td>
        </tr>
    </table>

    <p><a href="{% url 'djauction.views.view_auction' auction.id %}">Back To Auction Manager</a></p>

{% endblock %}

templates/djauction/viewuser.html
{% extends "djauction/base.html" %}
{% block content %}
    <h3>{{ auction_user.name }}</h3>
    {% if auction_user.address_1 %}
    {{auction_user.address_1}} {{auction_user.address_2}}<br>
    {% endif %}
    {% if auction_user.get_state_display %}
    {{auction_user.get_state_display}} {{auction_user.zip}}<br>
    {% endif %}
    {% if auction_user.phone %}
    {{auction_user.phone}}<br>
    {% endif %}
    {% if auction_user.email %}
    <a href="mailto:{{auction_user.email}}">{{auction_user.email}}</a><br>
    {% endif %}
    <h3>Donated Items</h3>
    {% for item in donated %}
		<a href="{% url 'djauction.views.view_item' item.id %}">{{item}}</a><br>
		{% empty %}
		No items found<br>
    {% endfor %}
    {% if auction %}
		{% if bids %}
			<h3>Bids</h3>
            <table>
			{% for bid in bids %}
            <tr>
			<td><a href="{% url 'djauction.views.view_item' bid.item.id %}">{{ bid.item }}</a></td>
            <td>{{ bid.ammount }}</td>
            </tr>
			{% endfor %}
            </table>
			Total: {{ owed|default:"0" }}<br>
		{% endif %}
		<p><a href="{% url 'djauction.views.add_item' auction.id auction_user.id %}">Add An Item</a></p>
        <p><a href="{% url 'djauction.views.checkout_user' auction.id auction_user.id %}">Check Out Current Bidder</a></p>
		<p><a href="{% url 'djauction.views.view_auction' auction.id %}">Return To Auction Manager</a></p>
    {% else %}
		<p><a href="{% url 'djauction.views.index' %}">Return To Index</a></p>
    {% endif %}
{% endblock %}